config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users
  # root 'devise/registrations#create'
  get 'books/index'
  get 'books/show'
  get 'books/new'
  get 'books/create'
  get 'books/edit'
  get 'books/update'
  get 'books/destroy'
  
  resources :books  
 root 'books#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    validates :name, presence: true     
    validates :author, presence: true   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :set_book, only:[:show, :edit, :update, :destroy]

    def show
    end
  
    def index
      @books = Book.all
    end
  
    def new
      @book = Book.new
    end

    def edit
     
    end
  
    def create
      @book = Book.new(book_params)
      if @book.save
        flash[:notice] = "book data created successfully."
        redirect_to @book
      else
        render 'new'
      end
    end

    def update
     
        if @book.update(book_params)
            flash[:notice] = "book detail updated succesfully."
            redirect_to @book
        else
            render 'edit'
        end
    end

    def destroy
     
      @book.destroy
      redirect_to books_path
      end

      #************************ make a prive methods for minimize the redudancy /clean up code
      private

      def set_book
        @book = Book.find(params[:id])
      end

      def book_params
        params.require(:book).permit(:name, :author ,:assign, :sell)
      end
  
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: @book, data: {turbo:false})  do |f| %>
  
    <p>
      <%= f.label :Book_name %><br/>
      <%= f.text_field :name %>
    </p>
  
    <p>
      <%= f.label :author %><br/>
      <%= f.text_area :author %>
    </p>

     <p>
      <%= f.label :assign %><br/>
      <%= f.text_area :assign %>
    </p>

     <p>
      <%= f.label :sell %><br/>
      <%= f.text_area :sell %>
    </p>
  
    <p>
      <%= f.submit %>
    </p>
  
  <% end %>

app/views/books/create.html.erb
<h1>This is a book Library</h1>
<p>please add New Book Detail</p>
<%= render 'form' %>
<%=link_to'home',root_path, class:"btn btn-dark"%>

app/views/books/edit.html.erb
<div class="alert alert-primary" role="alert">
<h1>Edit the book Detail</h1>
</div>

<%= render 'form' %>
<%=link_to'home',root_path, class:"btn btn-dark"%>

app/views/books/index.html.erb
<h1>This is a Book Library</h1>
<p>All book Details here </p>


<p><mark>Listing book details</p>

<table class="table table-hover">
<thead>
  <tr>
    <th scope="col">BOOK-NAME</th>
    <th scope="col">AUTHOR NAME</th>
    <th scope="col" >ASSIGN BY</th>
    <th scope="col" >SELL BY</th>
    <th scope="col" >Action</th>
  </tr></thead>
<% @books.each do |book| %>
    <tr>
      <td scope="row" ><%= book.name %></td>
      <td><%= book.author %></td>
      <td><%= book.assign %></td>
      <td><%= book.sell %></td>
      <td><%= link_to 'edit',edit_book_path(book),class:"btn btn-warning" %>
      <%= link_to 'delete',book_path(book), method: :delete, class:"btn btn-danger" %>
      <%= link_to 'show' , book_path(book), class:"btn btn-info" %>
      </td>
    </tr>
<% end %>
</table>
<%= link_to "+New book", new_book_path , class:"btn btn-success" %>

app/views/books/new.html.erb
<h1><mark>This is a book Libabry<mark></h1>
<div class="alert alert-info" role="alert">
<p>please add new book detail</p></div>
<%= render 'form' %>
<%=link_to'home',root_path, class:"btn btn-dark"%>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>
<%= render 'form' %>
<%= link_to "New book", new_book_path %>
<%=link_to'home',root_path, class:"btn btn-dark"%>